# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/louis/Desktop/AMNS_IMPLEMENTATION/VIVADO/AMNS_arith_co_design/AMNS_arith_co_design.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_25M_0/design_1_rst_ps7_0_25M_0.xci
# IP: The module: 'design_1_rst_ps7_0_25M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/louis/Desktop/AMNS_IMPLEMENTATION/VIVADO/AMNS_arith_co_design/AMNS_arith_co_design.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_25M_0/design_1_rst_ps7_0_25M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_25M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/louis/Desktop/AMNS_IMPLEMENTATION/VIVADO/AMNS_arith_co_design/AMNS_arith_co_design.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_25M_0/design_1_rst_ps7_0_25M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_25M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/louis/Desktop/AMNS_IMPLEMENTATION/VIVADO/AMNS_arith_co_design/AMNS_arith_co_design.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_25M_0/design_1_rst_ps7_0_25M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_25M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/louis/Desktop/AMNS_IMPLEMENTATION/VIVADO/AMNS_arith_co_design/AMNS_arith_co_design.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_25M_0/design_1_rst_ps7_0_25M_0.xci
# IP: The module: 'design_1_rst_ps7_0_25M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/louis/Desktop/AMNS_IMPLEMENTATION/VIVADO/AMNS_arith_co_design/AMNS_arith_co_design.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_25M_0/design_1_rst_ps7_0_25M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_25M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/louis/Desktop/AMNS_IMPLEMENTATION/VIVADO/AMNS_arith_co_design/AMNS_arith_co_design.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_25M_0/design_1_rst_ps7_0_25M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_25M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/louis/Desktop/AMNS_IMPLEMENTATION/VIVADO/AMNS_arith_co_design/AMNS_arith_co_design.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_25M_0/design_1_rst_ps7_0_25M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_25M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
